name: PyPi Release

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: "[3.5] Set up Python"
      uses: actions/setup-python@v2
      with: { python-version: 3.5 }
    - name: "[3.5] Install dependencies"
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: "[3.5] Build"
      run: python setup.py sdist bdist_wheel

    - name: "[2.7] Set up Python"
      uses: actions/setup-python@v2
      with: { python-version: 2.7 }
    - name: "[2.7] Install dependencies"
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: "[2.7] Build"
      run: python setup.py sdist bdist_wheel

    - name: Publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: twine upload dist/*
